import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif']);

// Album-only overrides live under the top-level `albums` key in scripts/portfolio.overrides.json.
const OVERRIDES_FILE = path.join(process.cwd(), 'scripts', 'portfolio.overrides.json');

async function readOverrides() {
  try {
    const raw = await fs.readFile(OVERRIDES_FILE, 'utf8');
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== 'object') return {};
    const albumOverrides = parsed?.albums;
    return albumOverrides && typeof albumOverrides === 'object' ? albumOverrides : {};
  } catch {
    return {};
  }
}

function toPosix(p) {
  return p.replace(/\\/g, '/');
}

function humanizeSegment(segment) {
  const raw = String(segment ?? '').trim();
  if (!raw) return '';
  return raw
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .split(' ')
    .map((w) => w.slice(0, 1).toUpperCase() + w.slice(1))
    .join(' ');
}

function titleFromSlug(slug) {
  const parts = slug.split('/').filter(Boolean).map(humanizeSegment).filter(Boolean);
  return parts.join(' / ') || 'Album';
}

function fileToLabel(fileName) {
  return fileName
    .replace(/\.[^.]+$/, '')
    .replace(/[_-]+/g, ' ')
    .toUpperCase();
}

function xmur3(str) {
  let h = 1779033703 ^ str.length;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return () => {
    h = Math.imul(h ^ (h >>> 16), 2246822507);
    h = Math.imul(h ^ (h >>> 13), 3266489909);
    return (h ^= h >>> 16) >>> 0;
  };
}

function stableNumericId(input) {
  // 32-bit stable hash, offset to reduce collision with portfolio numeric IDs.
  const h = xmur3(input)();
  return 2_000_000_000 + (h % 1_000_000_000);
}

async function listAlbums(albumsDir) {
  /** @type {{slug: string, absDir: string, files: string[]}[]} */
  const out = [];

  async function walk(dirAbs) {
    const entries = await fs.readdir(dirAbs, { withFileTypes: true });

    const imageFiles = entries
      .filter((e) => e.isFile())
      .map((e) => e.name)
      .filter((name) => IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase()))
      .sort((a, b) => a.localeCompare(b));

    const relDir = toPosix(path.relative(albumsDir, dirAbs));

    // Treat every directory that contains images as an album.
    if (imageFiles.length > 0) {
      // Use "misc" slug when images are placed directly in public/albums.
      const slug = relDir && relDir !== '.' ? relDir : 'misc';
      out.push({ slug, absDir: dirAbs, files: imageFiles });
    }

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      await walk(path.join(dirAbs, entry.name));
    }
  }

  await walk(albumsDir);
  out.sort((a, b) => a.slug.localeCompare(b.slug));
  return out;
}

function toTsLiteral(value) {
  return JSON.stringify(value, null, 2);
}

async function main() {
  const albumsDir = path.join(process.cwd(), 'public', 'albums');
  const outFile = path.join(process.cwd(), 'src', 'data', 'albums.generated.ts');
  const overrides = await readOverrides();

  let stats;
  try {
    stats = await fs.stat(albumsDir);
  } catch {
    stats = null;
  }

  if (!stats || !stats.isDirectory()) {
    const header = `// This file is auto-generated by scripts/generate-albums.mjs\n// Do not edit manually.\n\n`;
    const content =
      header +
      `export interface AlbumItem {\n` +
      `  id: number;\n` +
      `  src: string;\n` +
      `  fileName: string;\n` +
      `  alt: string;\n` +
      `  label: string;\n` +
      `  isCover?: boolean;\n` +
      `}\n\n` +
      `export interface Album {\n` +
      `  slug: string;\n` +
      `  title: string;\n` +
      `  items: AlbumItem[];\n` +
      `}\n\n` +
      `export const albums: Album[] = [] as const;\n\n` +
      `export default albums;\n`;

    await fs.mkdir(path.dirname(outFile), { recursive: true });
    await fs.writeFile(outFile, content, 'utf8');
    console.log('No public/albums directory found. Generated empty albums list.');
    return;
  }

  const dirs = await listAlbums(albumsDir);

  const albums = dirs.map((dir) => {
    const title = titleFromSlug(dir.slug);
    const items = dir.files.map((fileName) => {
      const rel = dir.slug === 'misc' ? fileName : `${dir.slug}/${fileName}`;
      const src = `/albums/${rel}`;

      const override = overrides?.[rel] ?? null;
      const overrideLabel = typeof override?.label === 'string' && override.label.trim() ? override.label.trim() : null;
      const overrideAlt = typeof override?.alt === 'string' && override.alt.trim() ? override.alt.trim() : null;
      const isCover = Boolean(override?.isCover);

      const label = overrideLabel ?? fileToLabel(fileName);
      const alt = overrideAlt ?? `${title} — ${label}`;

      return {
        id: stableNumericId(src),
        src,
        fileName,
        alt,
        label,
        isCover,
      };
    });

    // Prefer a single explicitly-marked cover.
    const coverIndex = items.findIndex((i) => i.isCover);
    if (coverIndex > 0) {
      const cover = items.splice(coverIndex, 1)[0];
      items.unshift(cover);
    }

    return {
      slug: dir.slug,
      title,
      items,
    };
  });

  const header = `// This file is auto-generated by scripts/generate-albums.mjs\n// Do not edit manually.\n\n`;
  const content =
    header +
    `export interface AlbumItem {\n` +
    `  id: number;\n` +
    `  src: string;\n` +
    `  fileName: string;\n` +
    `  alt: string;\n` +
    `  label: string;\n` +
    `  isCover?: boolean;\n` +
    `}\n\n` +
    `export interface Album {\n` +
    `  slug: string;\n` +
    `  title: string;\n` +
    `  items: AlbumItem[];\n` +
    `}\n\n` +
    `export const albums: Album[] = ${toTsLiteral(albums)} as const;\n\n` +
    `export default albums;\n`;

  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, content, 'utf8');
  console.log(`Generated ${path.relative(process.cwd(), outFile)} with ${albums.length} albums.`);
}

await main();
