// This file is auto-generated by scripts/generate-albums.mjs
// Do not edit manually.

export interface AlbumItem {
  id: number;
  src: string;
  fileName: string;
  alt: string;
  label: string;
  isCover?: boolean;
}

export interface Album {
  slug: string;
  title: string;
  items: AlbumItem[];
}

export const albums: Album[] = [
  {
    "slug": "our20s",
    "title": "Our20s",
    "items": [
      {
        "id": 2652168656,
        "src": "/albums/our20s/ted_443.jpeg",
        "fileName": "ted_443.jpeg",
        "alt": "Our20s — TED 443",
        "label": "TED 443",
        "isCover": true
      },
      {
        "id": 2760226426,
        "src": "/albums/our20s/ted_15.jpeg",
        "fileName": "ted_15.jpeg",
        "alt": "Our20s — TED 15",
        "label": "TED 15",
        "isCover": false
      },
      {
        "id": 2219216114,
        "src": "/albums/our20s/ted_182.jpeg",
        "fileName": "ted_182.jpeg",
        "alt": "Our20s — TED 182",
        "label": "TED 182",
        "isCover": false
      },
      {
        "id": 2280954407,
        "src": "/albums/our20s/ted_233.jpeg",
        "fileName": "ted_233.jpeg",
        "alt": "Our20s — TED 233",
        "label": "TED 233",
        "isCover": false
      },
      {
        "id": 2365271411,
        "src": "/albums/our20s/ted_245.jpeg",
        "fileName": "ted_245.jpeg",
        "alt": "Our20s — TED 245",
        "label": "TED 245",
        "isCover": false
      },
      {
        "id": 2125512536,
        "src": "/albums/our20s/ted_254.jpeg",
        "fileName": "ted_254.jpeg",
        "alt": "Our20s — TED 254",
        "label": "TED 254",
        "isCover": false
      },
      {
        "id": 2193401522,
        "src": "/albums/our20s/ted_291.jpeg",
        "fileName": "ted_291.jpeg",
        "alt": "Our20s — TED 291",
        "label": "TED 291",
        "isCover": false
      },
      {
        "id": 2815193818,
        "src": "/albums/our20s/ted_32.jpeg",
        "fileName": "ted_32.jpeg",
        "alt": "Our20s — TED 32",
        "label": "TED 32",
        "isCover": false
      },
      {
        "id": 2150486020,
        "src": "/albums/our20s/ted_337.jpeg",
        "fileName": "ted_337.jpeg",
        "alt": "Our20s — TED 337",
        "label": "TED 337",
        "isCover": false
      },
      {
        "id": 2403966168,
        "src": "/albums/our20s/ted_375.jpeg",
        "fileName": "ted_375.jpeg",
        "alt": "Our20s — TED 375",
        "label": "TED 375",
        "isCover": false
      },
      {
        "id": 2416114641,
        "src": "/albums/our20s/ted_378.jpeg",
        "fileName": "ted_378.jpeg",
        "alt": "Our20s — TED 378",
        "label": "TED 378",
        "isCover": false
      },
      {
        "id": 2803083877,
        "src": "/albums/our20s/ted_46.jpeg",
        "fileName": "ted_46.jpeg",
        "alt": "Our20s — TED 46",
        "label": "TED 46",
        "isCover": false
      },
      {
        "id": 2678685371,
        "src": "/albums/our20s/ted_484.jpeg",
        "fileName": "ted_484.jpeg",
        "alt": "Our20s — TED 484",
        "label": "TED 484",
        "isCover": false
      },
      {
        "id": 2218273835,
        "src": "/albums/our20s/ted_54.jpeg",
        "fileName": "ted_54.jpeg",
        "alt": "Our20s — TED 54",
        "label": "TED 54",
        "isCover": false
      },
      {
        "id": 2571811676,
        "src": "/albums/our20s/ted_640.jpeg",
        "fileName": "ted_640.jpeg",
        "alt": "Our20s — TED 640",
        "label": "TED 640",
        "isCover": false
      },
      {
        "id": 2027077485,
        "src": "/albums/our20s/ted_69.jpeg",
        "fileName": "ted_69.jpeg",
        "alt": "Our20s — TED 69",
        "label": "TED 69",
        "isCover": false
      },
      {
        "id": 2552519459,
        "src": "/albums/our20s/ted_710.jpeg",
        "fileName": "ted_710.jpeg",
        "alt": "Our20s — TED 710",
        "label": "TED 710",
        "isCover": false
      },
      {
        "id": 2564465657,
        "src": "/albums/our20s/ted_711.jpeg",
        "fileName": "ted_711.jpeg",
        "alt": "Our20s — TED 711",
        "label": "TED 711",
        "isCover": false
      },
      {
        "id": 2941417119,
        "src": "/albums/our20s/ted_718.jpeg",
        "fileName": "ted_718.jpeg",
        "alt": "Our20s — TED 718",
        "label": "TED 718",
        "isCover": false
      },
      {
        "id": 2056930002,
        "src": "/albums/our20s/ted_725.jpeg",
        "fileName": "ted_725.jpeg",
        "alt": "Our20s — TED 725",
        "label": "TED 725",
        "isCover": false
      },
      {
        "id": 2071828902,
        "src": "/albums/our20s/ted_751.jpeg",
        "fileName": "ted_751.jpeg",
        "alt": "Our20s — TED 751",
        "label": "TED 751",
        "isCover": false
      },
      {
        "id": 2610466069,
        "src": "/albums/our20s/ted_844.jpeg",
        "fileName": "ted_844.jpeg",
        "alt": "Our20s — TED 844",
        "label": "TED 844",
        "isCover": false
      },
      {
        "id": 2717827420,
        "src": "/albums/our20s/ted_882.jpeg",
        "fileName": "ted_882.jpeg",
        "alt": "Our20s — TED 882",
        "label": "TED 882",
        "isCover": false
      },
      {
        "id": 2264939503,
        "src": "/albums/our20s/ted_94.jpeg",
        "fileName": "ted_94.jpeg",
        "alt": "Our20s — TED 94",
        "label": "TED 94",
        "isCover": false
      }
    ]
  }
] as const;

export default albums;
