// This file is auto-generated by scripts/generate-portfolio.mjs
// Do not edit manually.

export type PortfolioCategory = "Concept" | "Event" | "Scene" | "Street";

export interface ExifSummary {
  shutterSpeed?: string;
  iso?: number;
  aperture?: string;
  camera?: string;
  lens?: string;
  focalLengthMm?: number;
  focalLength35Mm?: number;
  width?: number;
  height?: number;
  flashFired?: boolean;
}

export interface PortfolioItem {
  id: number;
  src: string;
  fileName: string;
  alt: string;
  label: string;
  category: PortfolioCategory;
  hideOnHome?: boolean;
  tags?: string[];
  exif: ExifSummary | null;
}

export const portfolioItems: PortfolioItem[] = [
  {
    "id": 1,
    "src": "/images/event/ted_101.jpeg",
    "fileName": "ted_101.jpeg",
    "label": "Girls of Summer",
    "alt": "Girls sharing a moment of shared joy with their surfboard at the beach.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/30",
      "iso": 400,
      "aperture": "f/3.5",
      "camera": "Nikon Nikomat FTN",
      "lens": "Nikon Series E 36-72mm f/3.5",
      "focalLengthMm": 72,
      "width": 1800,
      "height": 2400
    }
  },
  {
    "id": 2,
    "src": "/images/event/ted_103.jpeg",
    "fileName": "ted_103.jpeg",
    "label": "Focus",
    "alt": "Event shift. Just me doing my thing. Grateful for the team..",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/100",
      "iso": 200,
      "aperture": "f/2",
      "camera": "Canon EOS 700D",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "focalLengthMm": 35,
      "width": 2400,
      "height": 1349
    }
  },
  {
    "id": 3,
    "src": "/images/scene/ted_106.jpeg",
    "fileName": "ted_106.jpeg",
    "label": "Midnight Campus",
    "alt": "Late night at TDTU.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "University"
    ],
    "exif": {
      "shutterSpeed": "1/13",
      "iso": 6400,
      "aperture": "f/8",
      "camera": "Canon EOS R50",
      "lens": "RF-S18-45mm F4.5-6.3 IS STM",
      "focalLengthMm": 45,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 4,
    "src": "/images/event/ted_11.jpeg",
    "fileName": "ted_11.jpeg",
    "label": "Deep in Thought",
    "alt": "The silent grind behind the scenes.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/80",
      "iso": 200,
      "aperture": "f/8",
      "camera": "Canon EOS 5D Mark III",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 105,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 5,
    "src": "/images/scene/ted_114.jpeg",
    "fileName": "ted_114.jpeg",
    "label": "City on Fire",
    "alt": "A quiet night suddenly lit up like a dream.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "4s",
      "iso": 100,
      "aperture": "f/5",
      "camera": "Canon EOS RP",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "focalLengthMm": 35,
      "width": 1550,
      "height": 1937
    }
  },
  {
    "id": 6,
    "src": "/images/scene/ted_127.jpeg",
    "fileName": "ted_127.jpeg",
    "label": "Chasing Colors",
    "alt": "木漏れ日 (Komorebi)",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/320",
      "iso": 100,
      "aperture": "f/7.1",
      "camera": "Canon EOS RP",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "focalLengthMm": 35,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 7,
    "src": "/images/scene/ted_129.jpeg",
    "fileName": "ted_129.jpeg",
    "label": "Emerald Oasis",
    "alt": "A moment of perfect peace.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Nature"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 200,
      "aperture": "f/8",
      "camera": "Canon EOS RP",
      "lens": "Canon EF 50mm f/1.8 STM",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 8,
    "src": "/images/event/ted_133.jpeg",
    "fileName": "ted_133.jpeg",
    "label": "Quiet Connection",
    "alt": "It’s not just a competition.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 320,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "EF70-200mm f/2.8L IS II USM",
      "focalLengthMm": 123,
      "width": 1800,
      "height": 2400
    }
  },
  {
    "id": 9,
    "src": "/images/scene/ted_14.jpeg",
    "fileName": "ted_14.jpeg",
    "label": "Afterglow",
    "alt": "A burning sky to wrap up the day.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "University"
    ],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 1000,
      "aperture": "f/2.8",
      "camera": "Apple iPhone 15 Pro Max",
      "lens": "iPhone 15 Pro Max back triple camera 15.66mm f/2.8",
      "width": 2400,
      "height": 1800
    }
  },
  {
    "id": 10,
    "src": "/images/concept/ted_142.jpeg",
    "fileName": "ted_142.jpeg",
    "label": "Golden Girls",
    "alt": "The best times are the unplanned ones.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Pre-grad"
    ],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 400,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "Sigma 85mm F1.4 DG HSM | A (Canon EF)",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 11,
    "src": "/images/scene/ted_149.jpeg",
    "fileName": "ted_149.jpeg",
    "label": "Midnight Traffic",
    "alt": "The city never really sleeps, just slows down a bit.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "City"
    ],
    "exif": {
      "shutterSpeed": "1/40",
      "iso": 1000,
      "aperture": "f/2.8",
      "camera": "Apple iPhone 15 Pro Max",
      "lens": "iPhone 15 Pro Max back triple camera 15.66mm f/2.8",
      "focalLengthMm": 15.659999847383,
      "focalLength35Mm": 120,
      "width": 2268,
      "height": 4032
    }
  },
  {
    "id": 12,
    "src": "/images/street/ted_16.jpeg",
    "fileName": "ted_16.jpeg",
    "label": "Old Souls",
    "alt": "Film camera and wooden walls.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 640,
      "aperture": "f/1.8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 13,
    "src": "/images/concept/ted_178.jpeg",
    "fileName": "ted_178.jpeg",
    "label": "Chapter Closed",
    "alt": "Final goodbye to the sunny campus.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Pre-grad"
    ],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 400,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "Sigma 35mm F1.4 DG HSM | A (Canon EF)",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 14,
    "src": "/images/scene/ted_184.jpeg",
    "fileName": "ted_184.jpeg",
    "label": "Window Light & Bản",
    "alt": "Enjoying the calm view and good coffee.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Coffee"
    ],
    "exif": {
      "shutterSpeed": "1/1250",
      "iso": 160,
      "aperture": "f/1.8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 15,
    "src": "/images/scene/ted_188.jpeg",
    "fileName": "ted_188.jpeg",
    "label": "Letting Our Dreams Soar",
    "alt": "Vibrant kites dancing gracefully against a clear blue sky.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/2000",
      "iso": 200,
      "aperture": "f/6.3",
      "camera": "Nikon Nikomat FTN",
      "lens": "Nikon Series E 36-72mm f/3.5",
      "focalLengthMm": 40,
      "width": 2400,
      "height": 1613
    }
  },
  {
    "id": 16,
    "src": "/images/scene/ted_19.jpeg",
    "fileName": "ted_19.jpeg",
    "label": "Silent Shore",
    "alt": "The best kind of reset. Grateful.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Nature"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 100,
      "aperture": "f/12",
      "camera": "Canon EOS 70D",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "width": 1800,
      "height": 2400
    }
  },
  {
    "id": 17,
    "src": "/images/scene/ted_219.jpeg",
    "fileName": "ted_219.jpeg",
    "label": "Rest Station",
    "alt": "The sun through the trees makes everything feel like a movie.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "University"
    ],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 100,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 18,
    "src": "/images/scene/ted_22.jpeg",
    "fileName": "ted_22.jpeg",
    "label": "A Timeless Vow",
    "alt": "The start of our story.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Wedding"
    ],
    "exif": {
      "shutterSpeed": "1/30",
      "iso": 400,
      "aperture": "f/5",
      "camera": "Canon EOS 70D",
      "lens": "EF-S18-135mm f/3.5-5.6 IS STM",
      "focalLengthMm": 72,
      "width": 1920,
      "height": 2400
    }
  },
  {
    "id": 19,
    "src": "/images/event/ted_220.jpeg",
    "fileName": "ted_220.jpeg",
    "label": "Signed & Sealed",
    "alt": "CEE Team & TED Team, leaving our little mark behind.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/80",
      "iso": 320,
      "aperture": "f/1.8",
      "camera": "Canon EOS R5",
      "lens": "RF50mm F1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1350
    }
  },
  {
    "id": 20,
    "src": "/images/concept/ted_230.jpeg",
    "fileName": "ted_230.jpeg",
    "label": "Thành An",
    "alt": "An's Graduation",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Graduation"
    ],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 500,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "Sigma 35mm F1.4 DG HSM | A (Canon EF)",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 21,
    "src": "/images/scene/ted_242.jpeg",
    "fileName": "ted_242.jpeg",
    "label": "Clouds Below",
    "alt": "Woke up above the clouds, everything felt softer.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Nature"
    ],
    "exif": {
      "shutterSpeed": "1/80",
      "iso": 100,
      "aperture": "f/3.5",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 6240,
      "height": 4161
    }
  },
  {
    "id": 22,
    "src": "/images/street/ted_247.jpeg",
    "fileName": "ted_247.jpeg",
    "label": "Saigon After Dark",
    "alt": "The simple joy taking in the view.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [
      "City"
    ],
    "exif": {
      "shutterSpeed": "1/50",
      "iso": 3200,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 35,
      "width": 1920,
      "height": 2400
    }
  },
  {
    "id": 23,
    "src": "/images/street/ted_251.jpeg",
    "fileName": "ted_251.jpeg",
    "label": "Station Life",
    "alt": "Morning rush at the Metro.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [
      "City"
    ],
    "exif": {
      "shutterSpeed": "1/200",
      "iso": 250,
      "aperture": "f/2.8",
      "camera": "OLYMPUS IMAGING CORP. E-M1",
      "lens": "LUMIX G VARIO 35-100/F2.8",
      "focalLengthMm": 93,
      "focalLength35Mm": 186,
      "width": 2400,
      "height": 1920,
      "flashFired": false
    }
  },
  {
    "id": 24,
    "src": "/images/scene/ted_253.jpeg",
    "fileName": "ted_253.jpeg",
    "label": "The Empty Chair",
    "alt": "Found a chair in the middle of nowhere, didn’t sit.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/125",
      "iso": 100,
      "aperture": "f/6.3",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 3553,
      "height": 2369
    }
  },
  {
    "id": 25,
    "src": "/images/street/ted_272.jpeg",
    "fileName": "ted_272.jpeg",
    "label": "Together we meet",
    "alt": "We looked up, hoping to catch something we couldn’t name.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 6400,
      "aperture": "f4",
      "camera": "Sony Alpha 6000",
      "lens": "Sony 16-50mmm f3.5-5.6 OSS Alpha E-mount",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 26,
    "src": "/images/concept/ted_277.jpeg",
    "fileName": "ted_277.jpeg",
    "label": "In Between Moments",
    "alt": "Nothing special happened, but I remember this clearly.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/30",
      "iso": 1000,
      "aperture": "f/1.4",
      "camera": "Canon EOS RP",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "focalLengthMm": 35,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 27,
    "src": "/images/event/ted_282.jpeg",
    "fileName": "ted_282.jpeg",
    "label": "Some moments speak in silhouette",
    "alt": "A striking monochrome frame of mystery, contrast, and presence.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 640,
      "aperture": "f/2.8",
      "camera": "OLYMPUS IMAGING CORP. E-M1",
      "lens": "LUMIX G VARIO 35-100/F2.8",
      "focalLengthMm": 100,
      "focalLength35Mm": 200,
      "width": 2400,
      "height": 1631,
      "flashFired": false
    }
  },
  {
    "id": 28,
    "src": "/images/scene/ted_283.jpeg",
    "fileName": "ted_283.jpeg",
    "label": "City Lights",
    "alt": "A captivating panoramic view of a bustling city illuminated by thousands of lights at night.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "City"
    ],
    "exif": {
      "shutterSpeed": "1/25",
      "iso": 1250,
      "aperture": "f/1.8",
      "camera": "Apple iPhone 15 Pro Max",
      "lens": "iPhone 15 Pro Max back camera 6.765mm f/1.78",
      "focalLengthMm": 6.764999865652793,
      "focalLength35Mm": 24,
      "width": 1349,
      "height": 2400
    }
  },
  {
    "id": 29,
    "src": "/images/street/ted_286.jpeg",
    "fileName": "ted_286.jpeg",
    "label": "Through My Lens",
    "alt": "Some memories only exist because I chose to keep them.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/35",
      "iso": 6400,
      "aperture": "f/3.5",
      "camera": "Fujifilm XA3",
      "lens": "XC 15-45mm f3.5-5.6 OIS PZ",
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 30,
    "src": "/images/scene/ted_293.jpeg",
    "fileName": "ted_293.jpeg",
    "label": "Peak Hikers",
    "alt": "A group of friends sharing a moment of triumph on a trip to Ninh Thuan.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "SOC2026"
    ],
    "exif": {
      "shutterSpeed": "1/1000",
      "iso": 400,
      "aperture": "f/6.3",
      "camera": "Nikon Nikomat FTN",
      "lens": "Nikon Series E 36-72mm f/3.5",
      "focalLengthMm": 72,
      "width": 2400,
      "height": 1613
    }
  },
  {
    "id": 31,
    "src": "/images/concept/ted_31.jpeg",
    "fileName": "ted_31.jpeg",
    "label": "A Quiet Chapter",
    "alt": "The simple joy of holding a physical book.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 100,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "Sigma 85mm F1.4 DG HSM | A (Canon EF)",
      "width": 1605,
      "height": 2400
    }
  },
  {
    "id": 32,
    "src": "/images/event/ted_316.jpeg",
    "fileName": "ted_316.jpeg",
    "label": "That's a Wrap!",
    "alt": "Rap Nguoc Sang. The Gala crew.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [
      "Rạp Ngược Sáng"
    ],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 640,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "Canon EF 24-105mm f/4L IS",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 33,
    "src": "/images/scene/ted_321.jpeg",
    "fileName": "ted_321.jpeg",
    "label": "Workspace Flow",
    "alt": "Beauty corner at Inspire Library",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "University"
    ],
    "exif": {
      "shutterSpeed": "1/125",
      "iso": 400,
      "aperture": "f/4.5",
      "camera": "Canon EOS RP",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "focalLengthMm": 35,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 34,
    "src": "/images/scene/ted_352.jpeg",
    "fileName": "ted_352.jpeg",
    "label": "Golden Hour People at Creative Park",
    "alt": "Everyone looked softer under this light.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Sunset"
    ],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 100,
      "aperture": "f/14",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1350
    }
  },
  {
    "id": 35,
    "src": "/images/scene/ted_354.jpeg",
    "fileName": "ted_354.jpeg",
    "label": "Wide Open",
    "alt": "Golden hour where the sand meets the water. Just breathing it all in.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Seashore"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 100,
      "aperture": "f/8",
      "camera": "Canon EOS 70D",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "width": 2400,
      "height": 1350
    }
  },
  {
    "id": 36,
    "src": "/images/event/ted_398.jpeg",
    "fileName": "ted_398.jpeg",
    "label": "Grace in the Dark",
    "alt": "A dance of light and shadow.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 400,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "EF70-200mm f/2.8L IS II USM",
      "focalLengthMm": 200,
      "width": 1800,
      "height": 2400
    }
  },
  {
    "id": 37,
    "src": "/images/scene/ted_401.jpeg",
    "fileName": "ted_401.jpeg",
    "label": "Quiet Reflections",
    "alt": "The world was loud, but this part stayed calm.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Sunset"
    ],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 100,
      "aperture": "f/22",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1350
    }
  },
  {
    "id": 38,
    "src": "/images/event/ted_41.jpeg",
    "fileName": "ted_41.jpeg",
    "label": "Pure Joy",
    "alt": "Moments like these.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [
      "TED DREAM 11"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 2000,
      "aperture": "f/2.8",
      "camera": "Canon EOS R5",
      "lens": "RF50mm F1.8 STM",
      "width": 2400,
      "height": 1350
    }
  },
  {
    "id": 39,
    "src": "/images/street/ted_412.jpeg",
    "fileName": "ted_412.jpeg",
    "label": "Through the Glass",
    "alt": "Found this frame while waiting for my turn to the train.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/100",
      "iso": 1000,
      "aperture": "f/2.8",
      "camera": "OLYMPUS IMAGING CORP. E-M1",
      "lens": "LUMIX G VARIO 35-100/F2.8",
      "focalLengthMm": 100,
      "focalLength35Mm": 200,
      "width": 2400,
      "height": 1920,
      "flashFired": false
    }
  },
  {
    "id": 40,
    "src": "/images/scene/ted_416.jpeg",
    "fileName": "ted_416.jpeg",
    "label": "Sunset Chill",
    "alt": "Sunset at Creative Park",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 200,
      "aperture": "f/9",
      "camera": "Nikon Nikomat FTN",
      "lens": "Nikon Series E 36-72mm f/3.5",
      "focalLengthMm": 40,
      "width": 2400,
      "height": 1613
    }
  },
  {
    "id": 41,
    "src": "/images/scene/ted_426.jpeg",
    "fileName": "ted_426.jpeg",
    "label": "Sundown Drifter",
    "alt": "Golden hour, a lone figure, and the quiet. Perfect.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/125",
      "iso": 640,
      "aperture": "f/8",
      "camera": "Canon EOS 70D",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 42,
    "src": "/images/concept/ted_440.jpeg",
    "fileName": "ted_440.jpeg",
    "label": "Woven",
    "alt": "A story told in silent touch",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "We"
    ],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 1000,
      "aperture": "f/3.5",
      "camera": "Canon EOS 700D",
      "lens": "EF-S18-55mm f/3.5-5.6 IS STM",
      "width": 2400,
      "height": 1598
    }
  },
  {
    "id": 43,
    "src": "/images/concept/ted_442.jpeg",
    "fileName": "ted_442.jpeg",
    "label": "Milestones",
    "alt": "Golden hour celebrations.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/500",
      "iso": 100,
      "aperture": "f/1.4",
      "camera": "Canon EOS RP",
      "lens": "Sigma 85mm F1.4 DG HSM | A (Canon EF)",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 44,
    "src": "/images/street/ted_444.jpeg",
    "fileName": "ted_444.jpeg",
    "label": "Piercing the Canopy",
    "alt": "Catching the exact moment the light breaks through the leaves.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 400,
      "aperture": "f/13",
      "camera": "Canon EOS RP",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 45,
    "src": "/images/street/ted_446.jpeg",
    "fileName": "ted_446.jpeg",
    "label": "Passing Through",
    "alt": "Just a stranger in a hurry.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 100,
      "aperture": "f/2.8",
      "camera": "OLYMPUS IMAGING CORP. E-M1",
      "lens": "LUMIX G VARIO 35-100/F2.8",
      "focalLengthMm": 64,
      "focalLength35Mm": 128,
      "width": 1800,
      "height": 2400,
      "flashFired": false
    }
  },
  {
    "id": 46,
    "src": "/images/concept/ted_450.jpeg",
    "fileName": "ted_450.jpeg",
    "label": "Sunny Smiles",
    "alt": "Captured from above. Long shadows, bright hearts on campus.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Pre-grad"
    ],
    "exif": {
      "shutterSpeed": "1/320",
      "iso": 100,
      "aperture": "f/2.2",
      "camera": "Canon EOS RP",
      "lens": "Sigma 85mm F1.4 DG HSM | A (Canon EF)",
      "focalLengthMm": 85,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 47,
    "src": "/images/concept/ted_451.jpeg",
    "fileName": "ted_451.jpeg",
    "label": "A Page of Peace",
    "alt": "A small moment with a good book and nothing else.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/1250",
      "iso": 100,
      "aperture": "f/1.4",
      "camera": "Canon EOS RP",
      "lens": "Sigma 85mm F1.4 DG HSM | A (Canon EF)",
      "focalLengthMm": 85,
      "width": 5878,
      "height": 3920
    }
  },
  {
    "id": 48,
    "src": "/images/event/ted_454.jpeg",
    "fileName": "ted_454.jpeg",
    "label": "Sparkling Harmony",
    "alt": "Watching the stage light up like a thousand stars.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 1250,
      "aperture": "f/4",
      "camera": "Canon EOS 6D Mark II",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 45,
      "width": 2400,
      "height": 1800
    }
  },
  {
    "id": 49,
    "src": "/images/concept/ted_464.jpeg",
    "fileName": "ted_464.jpeg",
    "label": "Graduation Hat",
    "alt": "A close-up of a dream coming true.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 100,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "Sigma 85mm F1.4 DG HSM | A (Canon EF)",
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 50,
    "src": "/images/event/ted_490.jpeg",
    "fileName": "ted_490.jpeg",
    "label": "Strangers",
    "alt": "Where strangers slowly became a team.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/80",
      "iso": 800,
      "aperture": "f/4",
      "camera": "Canon EOS R5",
      "lens": "RF50mm F1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1350
    }
  },
  {
    "id": 51,
    "src": "/images/event/ted_514.jpeg",
    "fileName": "ted_514.jpeg",
    "label": "Echoes of Us",
    "alt": "TED DREAM 11. Lost in their smiles",
    "category": "Event",
    "hideOnHome": false,
    "tags": [
      "TED DREAM 11"
    ],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 2500,
      "aperture": "f/4.5",
      "camera": "Canon EOS R5",
      "lens": "RF50mm F1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1350
    }
  },
  {
    "id": 52,
    "src": "/images/event/ted_528.jpeg",
    "fileName": "ted_528.jpeg",
    "label": "Lights in the Dark",
    "alt": "A thousand quiet stars in one room.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 1250,
      "aperture": "f/1.8",
      "camera": "Canon EOS RP",
      "lens": "RF50mm F1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 53,
    "src": "/images/concept/ted_531.jpeg",
    "fileName": "ted_531.jpeg",
    "label": "We Grew Here",
    "alt": "Different paths, same starting point.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/1250",
      "iso": 200,
      "aperture": "f/5",
      "camera": "Canon EOS RP",
      "lens": "Sigma 35mm F1.4 DG HSM | A (Canon EF)",
      "focalLengthMm": 35,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 54,
    "src": "/images/concept/ted_533.jpeg",
    "fileName": "ted_533.jpeg",
    "label": "This Was Us",
    "alt": "TED10day",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/1250",
      "iso": 400,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "width": 1799,
      "height": 2400
    }
  },
  {
    "id": 55,
    "src": "/images/event/ted_540.jpeg",
    "fileName": "ted_540.jpeg",
    "label": "Starlight Wings",
    "alt": "Watching the lights dance around her like a million stars.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 1000,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "EF70-200mm f/2.8L IS II USM",
      "focalLengthMm": 100,
      "width": 2400,
      "height": 1800
    }
  },
  {
    "id": 56,
    "src": "/images/event/ted_553.jpeg",
    "fileName": "ted_553.jpeg",
    "label": "Illuminated Milestones",
    "alt": "Tangible proof of the sleepless nights and relentless pushing. We really left our mark here.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [
      "Rạp Ngược Sáng"
    ],
    "exif": {
      "shutterSpeed": "1/125",
      "iso": 1250,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "Canon EF 24-105mm f/4L IS",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 57,
    "src": "/images/scene/ted_567.jpeg",
    "fileName": "ted_567.jpeg",
    "label": "Corner Light",
    "alt": "Sat here longer than I planned, just watching the light.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Funiture"
    ],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 100,
      "aperture": "f/2.5",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 5448,
      "height": 3632
    }
  },
  {
    "id": 58,
    "src": "/images/event/ted_571.jpeg",
    "fileName": "ted_571.jpeg",
    "label": "Inner Circle",
    "alt": "Capturing the purest of bonds.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/50",
      "iso": 100,
      "aperture": "f/3.5",
      "lens": "XC16-50mmF3.5-5.6 OIS II",
      "focalLengthMm": 16,
      "focalLength35Mm": 24,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 59,
    "src": "/images/scene/ted_574.jpeg",
    "fileName": "ted_574.jpeg",
    "label": "Art of Surrender",
    "alt": "Total, unbothered peace.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Animals"
    ],
    "exif": {
      "shutterSpeed": "1/80",
      "iso": 1250,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "Canon EF 24-105mm f/4L IS",
      "focalLengthMm": 92,
      "width": 2400,
      "height": 1347
    }
  },
  {
    "id": 60,
    "src": "/images/concept/ted_576.jpeg",
    "fileName": "ted_576.jpeg",
    "label": "Where the Light Stayed",
    "alt": "A quiet graduation moment, framed by shadow, silence, and golden light.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Pre-grad"
    ],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 400,
      "aperture": "f2.8",
      "camera": "Canon EOS RP",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "width": 2400,
      "height": 1538
    }
  },
  {
    "id": 61,
    "src": "/images/concept/ted_580.jpeg",
    "fileName": "ted_580.jpeg",
    "label": "Park walk",
    "alt": "A soft cinematic moment in the middle of green stillness.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/200",
      "iso": 400,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 62,
    "src": "/images/event/ted_584.jpeg",
    "fileName": "ted_584.jpeg",
    "label": "Paper & Sweat",
    "alt": "It’s the quiet validation of all the behind-the-scenes hustle",
    "category": "Event",
    "hideOnHome": false,
    "tags": [
      "Rạp Ngược Sáng"
    ],
    "exif": {
      "shutterSpeed": "1/125",
      "iso": 2000,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 63,
    "src": "/images/event/ted_61.jpeg",
    "fileName": "ted_61.jpeg",
    "label": "Red Spotlight",
    "alt": "The red dress, the movement, the smile.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 1000,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "EF70-200mm f/2.8L IS II USM",
      "focalLengthMm": 190,
      "width": 1800,
      "height": 2400
    }
  },
  {
    "id": 64,
    "src": "/images/street/ted_612.jpeg",
    "fileName": "ted_612.jpeg",
    "label": "Reflected Realities",
    "alt": "A Boy's Inner World",
    "category": "Street",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 200,
      "aperture": "f/5.6",
      "camera": "Nikon Nikomat FTN",
      "lens": "Nikon Series E 36-72mm f/3.5",
      "focalLengthMm": 72,
      "width": 2400,
      "height": 1613
    }
  },
  {
    "id": 65,
    "src": "/images/scene/ted_615.jpeg",
    "fileName": "ted_615.jpeg",
    "label": "Silent Shore",
    "alt": "Landscape",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Nature"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 400,
      "aperture": "f/12",
      "camera": "Canon EOS 70D",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 66,
    "src": "/images/event/ted_622.jpeg",
    "fileName": "ted_622.jpeg",
    "label": "Crimson Wings",
    "alt": "The red dress, the movement, and that electric energy.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 1000,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "EF70-200mm f/2.8L IS II USM",
      "focalLengthMm": 102,
      "width": 2400,
      "height": 1800
    }
  },
  {
    "id": 67,
    "src": "/images/scene/ted_624.jpeg",
    "fileName": "ted_624.jpeg",
    "label": "Running with the Wind",
    "alt": "Didn’t look back, just followed where the wind took me.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 100,
      "aperture": "f/8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1350
    }
  },
  {
    "id": 68,
    "src": "/images/scene/ted_625.jpeg",
    "fileName": "ted_625.jpeg",
    "label": "First Light",
    "alt": "Morning came quietly, I didn’t say anything.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Nature"
    ],
    "exif": {
      "shutterSpeed": "1/125",
      "iso": 100,
      "aperture": "f/9",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 4691,
      "height": 3285
    }
  },
  {
    "id": 69,
    "src": "/images/scene/ted_635.jpeg",
    "fileName": "ted_635.jpeg",
    "label": "Soft Eyes",
    "alt": "He looked at me like he had something to say.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Animals"
    ],
    "exif": {
      "shutterSpeed": "1/100",
      "iso": 100,
      "aperture": "f/1.8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 6240,
      "height": 4160
    }
  },
  {
    "id": 70,
    "src": "/images/event/ted_66.jpeg",
    "fileName": "ted_66.jpeg",
    "label": "Quiet focus before the noise",
    "alt": "Holding the moment together in silence.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [
      "Chạm Đông"
    ],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 4000,
      "aperture": "f/4",
      "camera": "Canon EOS R5",
      "lens": "RF70-200mm F4 L IS USM",
      "focalLengthMm": 200,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 71,
    "src": "/images/event/ted_666.jpeg",
    "fileName": "ted_666.jpeg",
    "label": "La Voix des Étoiles",
    "alt": "A singer's capturing the magic of music and its power to inspire.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/120",
      "iso": 1250,
      "aperture": "f/1.8",
      "camera": "Apple iPhone 15 Pro Max",
      "lens": "iPhone 15 Pro Max back camera 6.765mm f/1.78",
      "focalLengthMm": 120,
      "focalLength35Mm": 24,
      "width": 1350,
      "height": 2400
    }
  },
  {
    "id": 72,
    "src": "/images/scene/ted_672.jpeg",
    "fileName": "ted_672.jpeg",
    "label": "Quiet Companions",
    "alt": "Two generations just watching the afternoon slip by.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Animals"
    ],
    "exif": {
      "shutterSpeed": "1/500",
      "iso": 200,
      "aperture": "f/6.3",
      "camera": "Canon EOS 5D Mark III",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 40,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 73,
    "src": "/images/scene/ted_674.jpeg",
    "fileName": "ted_674.jpeg",
    "label": "Light on the Shelf",
    "alt": "Just a fragment of home.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Funiture"
    ],
    "exif": {
      "shutterSpeed": "1/200",
      "iso": 160,
      "aperture": "f/1.8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 74,
    "src": "/images/scene/ted_686.jpeg",
    "fileName": "ted_686.jpeg",
    "label": "Sanctuaire de la Solitude",
    "alt": "The quiet joy of solitude and the deep connection with oneself and nature, a sanctuary of the mind and heart.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 400,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "Sigma 35mm F1.4 DG HSM | A (Canon EF)",
      "focalLengthMm": 35,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 75,
    "src": "/images/scene/ted_687.jpeg",
    "fileName": "ted_687.jpeg",
    "label": "Bitexco at Dusk",
    "alt": "The city slowed down, just for a moment.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "City"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 200,
      "aperture": "f/9",
      "camera": "Canon EOS RP",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 105,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 76,
    "src": "/images/scene/ted_694.jpeg",
    "fileName": "ted_694.jpeg",
    "label": "On the Way Up",
    "alt": "Slow ride, good view, no rush.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Sky"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 100,
      "aperture": "f/8",
      "camera": "Canon EOS RP",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "focalLengthMm": 35,
      "width": 6240,
      "height": 4160
    }
  },
  {
    "id": 77,
    "src": "/images/concept/ted_698.jpeg",
    "fileName": "ted_698.jpeg",
    "label": "Main Character Energy",
    "alt": "Smiling like the ending was worth it.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Graduation"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 100,
      "aperture": "f/1.4",
      "camera": "Canon EOS RP",
      "lens": "85mm F1.4 DG HSM | Art 016",
      "focalLengthMm": 85,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 78,
    "src": "/images/concept/ted_700.jpeg",
    "fileName": "ted_700.jpeg",
    "label": "Walking into the path",
    "alt": "A quiet walk on the familiar green paths where it all began.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Graduation"
    ],
    "exif": {
      "shutterSpeed": "1/500",
      "iso": 100,
      "aperture": "f/1.4",
      "camera": "Canon EOS RP",
      "lens": "85mm F1.4 DG HSM | Art 016",
      "focalLengthMm": 85,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 79,
    "src": "/images/concept/ted_701.jpeg",
    "fileName": "ted_701.jpeg",
    "label": "Into the Light",
    "alt": "Some endings arrive like golden hour.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Pre-grad"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 400,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "width": 2400,
      "height": 1348
    }
  },
  {
    "id": 80,
    "src": "/images/street/ted_723.jpeg",
    "fileName": "ted_723.jpeg",
    "label": "City Blooms",
    "alt": "Finding a bit of softness in the middle of the daily rush.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/320",
      "iso": 200,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 105,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 81,
    "src": "/images/concept/ted_726.jpeg",
    "fileName": "ted_726.jpeg",
    "label": "Thành An",
    "alt": "An's Graduation",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Graduation"
    ],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 400,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "Sigma 85mm F1.4 DG HSM | A (Canon EF)",
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 82,
    "src": "/images/concept/ted_735.jpeg",
    "fileName": "ted_735.jpeg",
    "label": "Love, Loud and Unfiltered",
    "alt": "The kind of moment you never outgrow.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Graduation"
    ],
    "exif": {
      "shutterSpeed": "1/200",
      "iso": 125,
      "aperture": "f/1.4",
      "camera": "Canon EOS RP",
      "lens": "85mm F1.4 DG HSM | Art 016",
      "focalLengthMm": 85,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 83,
    "src": "/images/street/ted_737.jpeg",
    "fileName": "ted_737.jpeg",
    "label": "Dog",
    "alt": "Found this old friend resting by the road today.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [
      "Animals"
    ],
    "exif": {
      "shutterSpeed": "1/80",
      "iso": 100,
      "aperture": "f/2.8",
      "camera": "OLYMPUS IMAGING CORP. E-M1",
      "lens": "LUMIX G VARIO 35-100/F2.8",
      "focalLengthMm": 100,
      "focalLength35Mm": 200,
      "width": 2400,
      "height": 1920,
      "flashFired": false
    }
  },
  {
    "id": 84,
    "src": "/images/scene/ted_739.jpeg",
    "fileName": "ted_739.jpeg",
    "label": "Afternoon Stillness",
    "alt": "Everything felt calm, like time paused for a bit.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "University"
    ],
    "exif": {
      "width": 4096,
      "height": 2730
    }
  },
  {
    "id": 85,
    "src": "/images/event/ted_741.jpeg",
    "fileName": "ted_741.jpeg",
    "label": "After Hours",
    "alt": "Stayed a little longer than planned, didn’t regret it.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [
      "Friends"
    ],
    "exif": {
      "shutterSpeed": "1/30",
      "iso": 1000,
      "aperture": "f/2.2",
      "camera": "Điện thoại KUyên",
      "lens": "iPhone 12 front camera 23mm f/2.2",
      "width": 2048,
      "height": 1462
    }
  },
  {
    "id": 86,
    "src": "/images/event/ted_75.jpeg",
    "fileName": "ted_75.jpeg",
    "label": "In the Spotlight",
    "alt": "She stood where the light chose her.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/80",
      "iso": 1600,
      "aperture": "f/5.6",
      "camera": "Canon EOS 700D",
      "lens": "EF-S18-135mm f/3.5-5.6 IS STM",
      "focalLengthMm": 113,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 87,
    "src": "/images/concept/ted_754.jpeg",
    "fileName": "ted_754.jpeg",
    "label": "The Ones Who Made It Softer",
    "alt": "No spotlight felt brighter than this.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Graduation"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 400,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "85mm F1.4 DG HSM | Art 016",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 88,
    "src": "/images/scene/ted_76.jpeg",
    "fileName": "ted_76.jpeg",
    "label": "Ascending to New Heights",
    "alt": "A breathtaking view of a winding staircase leading up to a mountain peak.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/500",
      "iso": 400,
      "aperture": "f/6.3",
      "camera": "Canon EOS RP",
      "lens": "Canon EF 50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 1800,
      "height": 2400
    }
  },
  {
    "id": 89,
    "src": "/images/concept/ted_761.jpeg",
    "fileName": "ted_761.jpeg",
    "label": "We Stand Here",
    "alt": "TED10day",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/500",
      "iso": 100,
      "aperture": "f/5",
      "camera": "Canon EOS RP",
      "lens": "Sigma 35mm F1.4 DG HSM | A (Canon EF)",
      "focalLengthMm": 35,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 90,
    "src": "/images/concept/ted_772.jpeg",
    "fileName": "ted_772.jpeg",
    "label": "A Quiet Page",
    "alt": "A little girl and a book, the world felt slower.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/500",
      "iso": 100,
      "aperture": "f/1.8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 4326,
      "height": 2884
    }
  },
  {
    "id": 91,
    "src": "/images/scene/ted_792.jpeg",
    "fileName": "ted_792.jpeg",
    "label": "Torn Realities",
    "alt": "A wall pieced together by a hundred different stories.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/125",
      "iso": 100,
      "aperture": "f/3.5",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 92,
    "src": "/images/event/ted_808.jpeg",
    "fileName": "ted_808.jpeg",
    "label": "Making Memories",
    "alt": "Trip to Ninh Thuan",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 400,
      "aperture": "f/5.6",
      "camera": "Nikon Nikomat FTN",
      "lens": "Nikon Series E 36-72mm f/3.5",
      "focalLengthMm": 35,
      "width": 2400,
      "height": 1613
    }
  },
  {
    "id": 93,
    "src": "/images/event/ted_809.jpeg",
    "fileName": "ted_809.jpeg",
    "label": "Into the Light",
    "alt": "Arms around shoulders right before the rush begins.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/160",
      "iso": 640,
      "aperture": "f/3.5",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 94,
    "src": "/images/scene/ted_832.jpeg",
    "fileName": "ted_832.jpeg",
    "label": "Where the Wind Goes",
    "alt": "Nothing much, just standing there watching things move.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Nature"
    ],
    "exif": {
      "shutterSpeed": "1/320",
      "iso": 100,
      "aperture": "f/6.3",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 6240,
      "height": 4160
    }
  },
  {
    "id": 95,
    "src": "/images/street/ted_834.jpeg",
    "fileName": "ted_834.jpeg",
    "label": "The Observer",
    "alt": "Framing the one who frames the world.",
    "category": "Street",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/125",
      "iso": 400,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 105,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 96,
    "src": "/images/scene/ted_843.jpeg",
    "fileName": "ted_843.jpeg",
    "label": "Sunlit Hideaway",
    "alt": "Bản Coffee",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Funiture"
    ],
    "exif": {
      "shutterSpeed": "1/1250",
      "iso": 500,
      "aperture": "f/1.8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 97,
    "src": "/images/event/ted_859.jpeg",
    "fileName": "ted_859.jpeg",
    "label": "Unseen Pulse",
    "alt": "The quiet, nerve-wracking intensity in the dark that keeps the entire show breathing.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/30",
      "iso": 4000,
      "aperture": "f/4",
      "camera": "Canon EOS 5D Mark III",
      "lens": "Canon EF 24-105mm f/4L IS",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 98,
    "src": "/images/scene/ted_86.jpeg",
    "fileName": "ted_86.jpeg",
    "label": "No Bad Days",
    "alt": "We didn’t plan anything, just laughed a lot.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Animals"
    ],
    "exif": {
      "shutterSpeed": "1/200",
      "iso": 250,
      "aperture": "f/5.6",
      "camera": "Canon EOS RP",
      "lens": "EF-S18-135mm f/3.5-5.6 IS STM",
      "focalLengthMm": 135,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 99,
    "src": "/images/event/ted_863.jpeg",
    "fileName": "ted_863.jpeg",
    "label": "Tools of Mine",
    "alt": "Started small, but it meant everything.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/20",
      "iso": 1600,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 105,
      "width": 4590,
      "height": 3060
    }
  },
  {
    "id": 100,
    "src": "/images/scene/ted_868.jpeg",
    "fileName": "ted_868.jpeg",
    "label": "Call of the Sea",
    "alt": "Out off the grid",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/1250",
      "iso": 400,
      "aperture": "f/9",
      "camera": "Canon EOS RP",
      "lens": "Canon EF 50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 1416,
      "height": 2400
    }
  },
  {
    "id": 101,
    "src": "/images/event/ted_877.jpeg",
    "fileName": "ted_877.jpeg",
    "label": "Soulful Soles",
    "alt": "The miles, the hours, the exhaustion. These boots carried my weight and my heart today. Proud.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/200",
      "iso": 640,
      "aperture": "f/7.1",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 102,
    "src": "/images/concept/ted_880.jpeg",
    "fileName": "ted_880.jpeg",
    "label": "Simple Joys",
    "alt": "Nothing big, just a day that felt right.",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 100,
      "aperture": "f/1.8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 103,
    "src": "/images/event/ted_891.jpeg",
    "fileName": "ted_891.jpeg",
    "label": "Gaze of Youth",
    "alt": "Pointing at boundless horizons and unwritten futures.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/2000",
      "iso": 400,
      "aperture": "f/6.3",
      "camera": "Nikon Nikomat FTN",
      "lens": "Nikon Series E 36-72mm f/3.5",
      "width": 2400,
      "height": 1613
    }
  },
  {
    "id": 104,
    "src": "/images/scene/ted_903.jpeg",
    "fileName": "ted_903.jpeg",
    "label": "A Place I’ll Miss",
    "alt": "Didn’t think it would mean this much.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "University"
    ],
    "exif": {
      "shutterSpeed": "1/200",
      "iso": 100,
      "aperture": "f/5.6",
      "camera": "Canon EOS RP",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 28,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 105,
    "src": "/images/concept/ted_937.jpeg",
    "fileName": "ted_937.jpeg",
    "label": "Graduation Props",
    "alt": "Portfolio image Graduation Props",
    "category": "Concept",
    "hideOnHome": false,
    "tags": [
      "Graduation"
    ],
    "exif": {
      "shutterSpeed": "1/250",
      "iso": 400,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "Sigma 85mm F1.4 DG HSM | A (Canon EF)",
      "width": 2400,
      "height": 1600
    }
  },
  {
    "id": 106,
    "src": "/images/scene/ted_943.jpeg",
    "fileName": "ted_943.jpeg",
    "label": "Still There",
    "alt": "No matter how far we go, it’s always there.",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/100",
      "iso": 50,
      "aperture": "f/4.5",
      "camera": "Canon EOS RP",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 105,
      "width": 1349,
      "height": 2400
    }
  },
  {
    "id": 107,
    "src": "/images/event/ted_945.jpeg",
    "fileName": "ted_945.jpeg",
    "label": "Vũ Ngọc Bảo Khuê",
    "alt": "TOP20 NDSV lần 5 TDTU",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/400",
      "iso": 1000,
      "aperture": "f/2.8",
      "camera": "Canon EOS RP",
      "lens": "EF70-200mm f/2.8L IS II USM",
      "focalLengthMm": 200,
      "width": 2400,
      "height": 1800
    }
  },
  {
    "id": 108,
    "src": "/images/scene/ted_947.jpeg",
    "fileName": "ted_947.jpeg",
    "label": "Window Light & Bản",
    "alt": "Another aspect",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [
      "Coffee"
    ],
    "exif": {
      "shutterSpeed": "1/1250",
      "iso": 160,
      "aperture": "f/1.8",
      "camera": "Canon EOS RP",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 1600,
      "height": 2400
    }
  },
  {
    "id": 109,
    "src": "/images/event/ted_953.jpeg",
    "fileName": "ted_953.jpeg",
    "label": "Suspended Dream",
    "alt": "A fleeting act of weightless grace beneath the spotlight.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/125",
      "iso": 100,
      "aperture": "f/1.8",
      "camera": "Apple iPhone 15 Pro Max",
      "lens": "iPhone 15 Pro Max back camera 6.765mm f/1.78",
      "width": 1350,
      "height": 2400
    }
  },
  {
    "id": 110,
    "src": "/images/event/ted_959.jpeg",
    "fileName": "ted_959.jpeg",
    "label": "Under the Light",
    "alt": "For a moment, everything else faded away.",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/125",
      "iso": 1600,
      "aperture": "f/4",
      "camera": "Canon EOS RP",
      "lens": "EF24-105mm f/4L IS USM",
      "focalLengthMm": 105,
      "width": 3504,
      "height": 6229
    }
  },
  {
    "id": 111,
    "src": "/images/scene/ted_975.jpeg",
    "fileName": "ted_975.jpeg",
    "label": "Flower",
    "alt": "Perfect Focus",
    "category": "Scene",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/1600",
      "iso": 100,
      "aperture": "f/2.8",
      "lens": "EF50mm f/1.8 STM",
      "focalLengthMm": 50,
      "width": 1920,
      "height": 2400
    }
  },
  {
    "id": 112,
    "src": "/images/event/ted_976.jpeg",
    "fileName": "ted_976.jpeg",
    "label": "Trần Tín Đạt",
    "alt": "Nam Vương NDSV lần 5 TDTU",
    "category": "Event",
    "hideOnHome": false,
    "tags": [],
    "exif": {
      "shutterSpeed": "1/60",
      "iso": 200,
      "aperture": "f/2.8",
      "camera": "Canon EOS 700D",
      "lens": "35mm F1.4 DG HSM | Art 012",
      "focalLengthMm": 50,
      "width": 2400,
      "height": 1800
    }
  }
] as const;

export const portfolioCategories: PortfolioCategory[] = [
  "Concept",
  "Event",
  "Scene",
  "Street"
] as const;

export default portfolioItems;
